on : push
jobs : 
        second-job:
          runs-on : ubuntu-latest
          steps : 
                  - uses : actions/checkout@v4
                  - run : npm ci
                  - run : npx eslint .
                  - run : node --version
                  - run : npm --version
                  - run : node index.js
              